# Generated by Django 2.0.5 on 2019-02-23 00:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_product_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 0, 5, 0, 128379, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 0, 5, 0, 128347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='cleanup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 0, 5, 0, 127806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='setup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 0, 5, 0, 127771, tzinfo=utc)),
        ),
    ]
