# Generated by Django 2.0.5 on 2019-02-25 01:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20190222_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 1, 45, 14, 430296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 1, 45, 14, 430263, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='cleanup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 1, 45, 14, 429709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='setup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 1, 45, 14, 429675, tzinfo=utc)),
        ),
    ]
