# Generated by Django 2.0.5 on 2019-02-25 04:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190224_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 4, 56, 20, 175946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 4, 56, 20, 175911, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='cleanup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 4, 56, 20, 175309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='setup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 4, 56, 20, 175274, tzinfo=utc)),
        ),
    ]
