# Generated by Django 2.0.5 on 2019-02-25 05:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190224_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 5, 12, 15, 122341, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 5, 12, 15, 122307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='cleanup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 5, 12, 15, 121597, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='setup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 5, 12, 15, 121553, tzinfo=utc)),
        ),
    ]
