# Generated by Django 2.0.13 on 2019-03-26 23:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20190224_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 23, 1, 53, 594726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 23, 1, 53, 594675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='cleanup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 23, 1, 53, 593758, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='setup_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 23, 1, 53, 593706, tzinfo=utc)),
        ),
    ]
